# Generated by Django 4.2.6 on 2024-09-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorkBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='firstName',
            field=models.CharField(default='null', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='groupID',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='lastName',
            field=models.CharField(default='null', max_length=25),
            preserve_default=False,
        ),
    ]
