# Generated by Django 4.2.6 on 2024-09-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorkBoard', '0003_posts_postsreplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='groupID',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
