# Generated by Django 4.2.6 on 2024-09-06 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CorkBoard', '0004_posts_groupid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsreplies',
            name='postID',
        ),
    ]
