# Generated by Django 4.2.6 on 2024-09-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorkBoard', '0006_remove_posts_postid_postsreplies_postid'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='postID',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
