# Generated by Django 5.1.1 on 2024-09-27 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorkBoard', '0009_users_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.CharField(max_length=10)),
                ('chore', models.CharField(default='null', max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('description', models.CharField(default='No description...', max_length=255)),
                ('completer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completer', to='CorkBoard.users')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='CorkBoard.users')),
            ],
        ),
    ]
